const BACKEND_URL = (location.hostname === 'localhost' || location.hostname === '127.0.0.1')
  ? 'http://localhost:3001'
  : 'https://bffr.onrender.com';

(function keepAlive() {
  if (location.hostname === 'localhost' || location.hostname === '127.0.0.1') return;
  const ping = () => fetch(BACKEND_URL + '/ping').catch(() => {});
  ping();
  setInterval(ping, 5 * 60 * 1000);
})();

const CATS = {
  '😀': ['😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙','🥲','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🤐','🤨','😐','😑','😶','😶‍🌫️','😏','😒','🙄','😬','🤥','🫨','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','😵‍💫','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','🫤','😟','🙁','☹️','😮','😯','😲','😳','🥺','🥹','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖','😺','😸','😹','😻','😼','😽','🙀','😿','😾'],
  '👋': ['👋','🤚','🖐️','✋','🖖','🫱','🫲','🫳','🫴','👌','🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','🫵','👍','👎','✊','👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🫀','🫁','🧠','🦷','🦴','👀','👁️','👅','👄','🫦','💋','🧑','👶','🧒','👦','👧','🧑','👱','👨','🧔','👩','🧓','👴','👵','🙍','🙎','🙅','🙆','💁','🙋','🧏','🙇','🤦','🤷','💃','🕺','🧗','🏃','🚶','🧘','🧑‍🤝‍🧑','👫','👬','👭','💏','💑','🗣️','👤','👥'],
  '🐶': ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🦋','🐌','🐞','🐜','🪲','🐢','🐍','🦎','🐙','🦑','🦐','🦞','🦀','🪸','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🦧','🦣','🐘','🦛','🦏','🐪','🐫','🦒','🦘','🦬','🐃','🐂','🐄','🐎','🐖','🐏','🐑','🦙','🐐','🦌','🐕','🐩','🦮','🐈','🐓','🦃','🦤','🦚','🦜','🦢','🦩','🕊️','🐇','🦝','🦨','🦡','🦦','🦥','🐁','🐀','🐿️','🦔','🐾','🐉','🐲','🌵','🎄','🌲','🌳','🌴','🪵','🌱','🌿','☘️','🍀','🎍','🪴','🎋','🍃','🍂','🍁','🪺','🪹','🍄','🐚','🪸','🪨','🌾','💐','🌷','🌹','🥀','🪷','🌺','🌸','🌼','🌻','🌞','🌝','🌛','🌜','🌚','🌕','🌖','🌗','🌘','🌑','🌒','🌓','🌔','🌙','🌟','⭐','🌠','🌌','☀️','🌤️','⛅','🌥️','☁️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌬️','💨','💧','💦','🫧','☔','☂️','🌊','🌀','🌈','⚡','🔥'],
  '🍎': ['🍎','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🫒','🥑','🍆','🥦','🥬','🥒','🌶️','🫑','🧄','🧅','🥔','🌽','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖','🦴','🌭','🍔','🍟','🍕','🫓','🥪','🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🍝','🍜','🍲','🍛','🍣','🍱','🥟','🦪','🍤','🍙','🍘','🍥','🥮','🍢','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','🌰','🥜','🍯','🧃','🥤','🧋','☕','🫖','🍵','🧉','🍺','🍻','🥂','🍷','🫗','🥃','🍸','🍹','🍾','🧊','🥄','🍴','🍽️','🫙','🧂'],
  '⚽': ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🏓','🏸','🏒','🥍','🏏','🪃','🥅','⛳','🪁','🤿','🎯','🎳','🪀','🪆','🎮','🕹️','🎰','🧩','🎭','🎨','🖼️','🎬','🎤','🎧','🎼','🎹','🥁','🪘','🎷','🎺','🎸','🪗','🎻','🎲','♟️','🃏','🀄','🎪','🤹','🎠','🎡','🎢','🎟️','🎫','🏆','🥇','🥈','🥉','🏅','🎖️','🏵️','🎗️','🏋️','🤸','⛷️','🏂','🏋️','🤼','🤺','🤾','⛹️','🏊','🚣','🧗','🚵','🚴','🧘','🤸','🛹','🛷','🛼','🤽','🏇','🧜','🏄'],
  '🚗': ['🚗','🚕','🚙','🚌','🚎','🏎️','🚓','🚑','🚒','🛻','🚚','🚛','🚜','🏍️','🛵','🛺','🚲','🛴','🛹','🛼','🚏','🛣️','🛤️','⛽','🚨','🚥','🚦','🚧','⚓','🛟','⛵','🚤','🛥️','🛳️','⛴️','🚢','✈️','🛩️','🛫','🛬','🪂','💺','🚁','🚟','🚠','🚡','🛸','🚀','🛶','🚂','🚃','🚄','🚅','🚆','🚇','🚈','🚉','🚊','🚝','🚞','🚋','🚌','🚍','🚎','🗺️','🧭','🏔️','⛰️','🌋','🗻','🏕️','🏖️','🏜️','🏝️','🏞️','🏟️','🏛️','🏗️','🧱','🪨','🪵','🛖','🏘️','🏚️','🏠','🏡','🏢','🏣','🏤','🏥','🏦','🏨','🏩','🏪','🏫','🏬','🏭','🏯','🏰','💒','🗼','🗽','⛪','🕌','🛕','🕍','⛩️','🕋','⛲','⛺','🌁','🌃','🏙️','🌄','🌅','🌆','🌇','🌉','🎆','🎇','🗺️'],
  '💡': ['⌚','📱','📲','💻','⌨️','🖥️','🖨️','🖱️','🖲️','💽','💾','💿','📀','🧮','📷','📸','📹','🎥','📽️','🎞️','📞','☎️','📟','📠','📺','📻','🧭','⏱️','⏲️','⏰','🕰️','⌛','⏳','📡','🔋','🪫','🔌','💡','🔦','🕯️','🪔','💰','💴','💵','💶','💷','💸','💳','🪙','💎','⚖️','🪜','🧰','🪛','🔧','🔩','⚙️','🗜️','🔗','⛓️','🪝','🧲','🪄','🔑','🗝️','🔐','🔒','🔓','🪞','🪟','🛋️','🪑','🚽','🪠','🚿','🛁','🪤','🧴','🪒','🧹','🧺','🧻','🪣','🧼','🫧','🪥','🧯','🛒','🚪','📦','📫','📪','📬','📭','📮','🗳️','✏️','✒️','🖊️','🖋️','📝','📁','📂','🗂️','📅','📆','🗒️','🗓️','📇','📈','📉','📊','📋','📌','📍','📎','🖇️','📏','📐','✂️','🗃️','🗄️','🗑️','🔍','🔎','🔏','📚','📖','🔖','🏷️','💰','🧾'],
  '❤️': ['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','❤️‍🔥','❤️‍🩹','💔','💕','💞','💓','💗','💖','💘','💝','💟','🫀','♥️','♠️','♣️','♦️','🃏','✨','💫','⭐','🌟','💥','🔥','🌈','❄️','⚡','🌊','💨','🌀','☀️','🌙','☁️','💧','🍀','🌿','🌱','🌲','🌳','🌴','🌵','🌾','🍁','🍃','🌺','🌻','🌸','🌹','🥀','🌼','💐','🍄','🌏','🌍','🌎','🪐','⚫','⚪','🟤','🔴','🔵','🟢','🟡','🟠','🟣','🔺','🔻','🔶','🔷','🔸','🔹','🔲','🔳','▪️','▫️','◾','◽','◼️','◻️','🔈','🔉','🔊','📢','📣','🔔','🔕','🎵','🎶','💤','🛑','♻️','✅','❌','❎','🔱','⚜️','🏁','🚩','🎌','🏴','🏳️','🕊️','🏳️‍🌈','🏳️‍⚧️'],
  '🎉': ['🎉','🎊','🎈','🎀','🎁','🎗️','🎟️','🎫','🏮','🎐','🎑','🧧','🎆','🎇','✨','🎃','🎄','🎋','🎍','🎎','🎏','🎠','🎡','🎢','🎪','🤹','🎭','🎨','🖼️','🎬','🎤','🎧','🎼','🎹','🥁','🎷','🎺','🎸','🎻','🎲','🎯','🎳','🎮','🕹️','🃏','🀄','🧩','🪆','🪅','🎴','🔮','🪬','🧿','🪩'],
  '🧠': ['🧠','💊','💉','🩺','🩹','🩻','🩼','🦽','🦼','🧬','🔬','🔭','🧪','🧫','🧲','⚗️','🏥','👨‍⚕️','👩‍⚕️','👨‍🏫','👩‍🏫','👨‍🎨','👩‍🎨','👨‍💻','👩‍💻','👨‍🍳','👩‍🍳','👨‍🚀','👩‍🚀','👨‍✈️','👩‍✈️','🕵️','👮','💂','👷','🧑‍🚒','🧑‍🎤','🧑‍🎨','🧑‍🔬','🧑‍🏭','🧑‍💼','🧑‍🔧','🧑‍🌾','🧑‍🍳','🧑‍🏫','🧑‍⚕️','🧑‍🚀','🧑‍⚖️','🧙','🧚','🧛','🧜','🧝','🧞','🧟','🧌'],
};

// Deduplicate within each category, then build a globally unique pool
Object.keys(CATS).forEach(k => { CATS[k] = [...new Set(CATS[k])]; });
const ALL = [...new Set(Object.values(CATS).flat())];
const QLABEL = {
  '😀':'faces','👋':'people','🐶':'nature','🍎':'food & drink',
  '⚽':'activity','🚗':'travel','💡':'objects','❤️':'symbols',
  '🎉':'celebration','🧠':'roles & science'
};

// Keyword map for search — emoji → searchable terms
const EMOJI_KEYWORDS = {
  '😀':'happy grin smile','😃':'happy smile big','😄':'happy smile laugh','😁':'grin big happy',
  '😆':'laugh haha xd','😅':'sweat nervous awkward','🤣':'rofl laugh roll floor','😂':'cry laugh tears joy',
  '🙂':'slight smile ok','🥰':'love hearts adore','😍':'eyes love heart','🤩':'star eyes wow amazing',
  '😘':'kiss blow love','😚':'kiss closed eyes','😋':'yum delicious tongue','😛':'tongue out silly',
  '😜':'wink tongue silly','🤪':'zany crazy wild','😝':'tongue closed eyes','🤑':'money dollar eyes',
  '🤗':'hug happy arms','🤭':'oops mouth hand','🤫':'shh quiet secret silence','🤔':'thinking hmm wonder',
  '🤐':'zip mouth quiet sealed','😐':'neutral face meh','😶':'no mouth silent mute',
  '😏':'smirk sly knowing','😒':'unamused bored annoyed','🙄':'eye roll bored sigh',
  '😬':'grimace awkward nervous','🤥':'lying nose pinocchio','😌':'relieved peaceful calm',
  '😔':'pensive sad disappointed','😪':'sleepy tired drool','😴':'sleep zzz tired',
  '😷':'mask sick ill covid','🤒':'sick thermometer fever','🤕':'hurt head bandage',
  '🤢':'nausea sick gross green','🤮':'vomit sick gross puke','🤧':'sneeze tissue cold sick',
  '🥵':'hot sweating red face','🥶':'cold freezing blue','🥴':'woozy dizzy drunk','😵':'dizzy dead knocked out',
  '🤯':'mind blown explode wow','🤠':'cowboy hat western','🥳':'party celebrate hat',
  '😎':'cool sunglasses chill','🤓':'nerd glasses smart study','🧐':'monocle sophisticated',
  '😕':'confused worried face','😟':'worried concerned sad','🙁':'slightly frown sad',
  '☹️':'frown sad unhappy','😮':'surprised open mouth','😯':'hushed surprised',
  '😲':'astonished shocked wow','😳':'flushed embarrassed red','🥺':'pleading sad puppy eyes',
  '😦':'frowning open mouth shocked','😧':'anguished shocked worried','😨':'fearful scared blue',
  '😰':'anxious sweat scared','😥':'disappointed relieved sweat','😢':'cry sad single tear',
  '😭':'sob cry loud tears','😱':'scream fear shock munch','😖':'confounded frustrated',
  '😣':'persevering effort struggle','😞':'disappointed sad let down','😓':'downcast sweat worry',
  '😩':'weary tired sad','😫':'tired exhausted weary','🥱':'yawn tired bored sleepy',
  '😤':'steam angry huff nose','😡':'angry red mad','😠':'angry mad face',
  '🤬':'swearing angry cursing','😈':'devil evil purple horns smile','👿':'angry devil red horns',
  '💀':'skull death dead bones','☠️':'skull crossbones danger pirate','💩':'poop shit brown happy',
  '🤡':'clown joker silly red nose','👹':'ogre monster demon japanese','👺':'goblin tengu mask japanese',
  '👻':'ghost spooky halloween boo','👽':'alien ufo extraterrestrial','👾':'alien monster game pixel',
  '🤖':'robot bot machine android',
  '👋':'wave hello hi hand','🤚':'raised hand back stop','🖐️':'hand five fingers spread',
  '✋':'stop hand raised high five','🖖':'vulcan salute spock live long','👌':'ok perfect circle',
  '🤌':'chef kiss italian pinch','✌️':'peace victory two fingers','🤞':'cross fingers luck hope',
  '🤟':'love you ily sign language','🤘':'horns rock metal sign','🤙':'call me shaka hang loose',
  '👈':'point left arrow back','👉':'point right arrow next','👆':'point up above',
  '👇':'point down below','👍':'thumbs up like yes good','👎':'thumbs down dislike no bad',
  '✊':'fist bump power raised','👊':'punch oncoming fist hit','👏':'clap applause hands',
  '🙌':'hooray cheer raised hands celebration','🤝':'handshake deal agreement',
  '🙏':'pray thank you please folded hands','💪':'muscle strong flex bicep arm',
  '👀':'eyes looking watch see','👅':'tongue taste lick','👄':'lips mouth kiss red',
  '💋':'kiss mark lips print red',
  '🐶':'dog puppy pet animal','🐱':'cat kitten pet animal','🐭':'mouse animal rodent',
  '🐹':'hamster animal cute','🐰':'rabbit bunny hop','🦊':'fox clever animal',
  '🐻':'bear animal forest','🐼':'panda bear cute bamboo','🐨':'koala australia marsupial',
  '🐯':'tiger animal striped','🦁':'lion king safari wild','🐮':'cow moo farm animal',
  '🐷':'pig oink farm animal','🐸':'frog green jump ribbit','🐵':'monkey ape face animal',
  '🙈':'see no evil monkey','🙉':'hear no evil monkey','🙊':'speak no evil monkey',
  '🦋':'butterfly insect colorful wings','🐛':'bug caterpillar worm insect',
  '🐌':'snail slow shell','🐝':'bee honey sting insect','🐞':'ladybug ladybird insect red',
  '🐢':'turtle tortoise slow reptile','🐍':'snake reptile slither python',
  '🦎':'lizard reptile chameleon','🐙':'octopus tentacles ocean sea',
  '🦑':'squid tentacles ocean sea','🦀':'crab red seafood ocean','🐡':'blowfish puffer ocean fish',
  '🐠':'tropical fish clownfish nemo','🐟':'fish blue ocean sea','🐬':'dolphin ocean mammal jump',
  '🐳':'whale ocean blue spout','🦈':'shark ocean danger predator',
  '🐘':'elephant trunk big animal safari','🦒':'giraffe tall neck safari',
  '🐕':'dog pet animal loyal','🐈':'cat pet animal meow','🌵':'cactus desert plant',
  '🌲':'evergreen tree forest pine','🌳':'tree deciduous forest nature',
  '🌴':'palm tree tropical beach','🌱':'seedling sprout plant grow',
  '🌿':'herb leaf green plant','☘️':'shamrock clover luck irish','🍀':'four leaf clover lucky',
  '🍄':'mushroom fungus mario','🌸':'cherry blossom pink flower','🌹':'rose flower love red',
  '🌺':'hibiscus flower tropical red','🌻':'sunflower yellow happy bright',
  '🌼':'blossom flower white yellow','💐':'bouquet flowers love gift',
  '🌙':'moon crescent night sleep','⭐':'star yellow bright shine','🌟':'glowing star sparkle shine',
  '☀️':'sun sunny bright day warm','🌈':'rainbow colorful pride hope',
  '❄️':'snowflake cold winter freeze','⚡':'lightning bolt electric storm fast',
  '🔥':'fire hot burn flame passion','💧':'droplet water blue rain tear',
  '🌊':'wave ocean water surf sea',
  '🍎':'apple red fruit food','🍊':'orange citrus fruit','🍋':'lemon yellow citrus sour',
  '🍌':'banana yellow fruit tropical','🍉':'watermelon green red summer fruit',
  '🍇':'grapes purple wine fruit','🍓':'strawberry red sweet fruit',
  '🫐':'blueberry blue fruit','🍒':'cherry red fruit sweet pair',
  '🍑':'peach fruit fuzzy butt','🥭':'mango tropical fruit sweet',
  '🍍':'pineapple tropical fruit spiky','🥥':'coconut tropical white milk',
  '🥝':'kiwi green fruit fuzzy','🍅':'tomato red vegetable sauce',
  '🥑':'avocado green toast healthy','🍆':'eggplant purple vegetable aubergine',
  '🌽':'corn maize yellow vegetable','🥕':'carrot orange vegetable rabbit',
  '🥦':'broccoli green vegetable healthy','🧅':'onion vegetable tear cry',
  '🧄':'garlic spicy vegetable vampire','🥔':'potato vegetable brown fries',
  '🌶️':'pepper hot spicy chili red','🥚':'egg breakfast cook oval',
  '🍳':'frying pan egg cook breakfast','🥞':'pancakes breakfast stack maple',
  '🧇':'waffle breakfast sweet grid','🥓':'bacon pork breakfast meat strips',
  '🍔':'burger hamburger fast food beef','🍟':'french fries fast food potato',
  '🍕':'pizza slice italian cheese','🌮':'taco mexican shell meat',
  '🌯':'burrito wrap tortilla roll','🍝':'spaghetti pasta italian noodles',
  '🍜':'ramen noodles soup japanese bowl','🍣':'sushi rice fish japanese roll',
  '🍦':'ice cream soft serve sweet','🍰':'cake slice birthday sweet dessert',
  '🎂':'birthday cake candles celebrate','🍩':'donut ring sweet glaze',
  '🍪':'cookie chocolate chip sweet','🍫':'chocolate candy sweet brown',
  '🍬':'candy sweet lollipop colorful','🍭':'lollipop candy stick sweet spiral',
  '☕':'coffee hot drink cafe morning','🍵':'tea hot drink leaf green cup',
  '🧋':'boba milk tea bubble drink','🍺':'beer mug drink alcohol yellow',
  '🍻':'cheers toast beer mugs drink','🥂':'champagne toast celebrate clink',
  '🍷':'wine red glass drink alcohol','🍸':'cocktail martini drink mix',
  '🍾':'champagne bottle celebrate cork pop',
  '⚽':'soccer ball football sport kick','🏀':'basketball sport orange bounce',
  '🏈':'american football sport nfl','⚾':'baseball sport bat pitcher',
  '🎾':'tennis ball sport racket','🏐':'volleyball sport beach net',
  '🎱':'billiards pool 8 ball cue','🏓':'ping pong table tennis paddle',
  '🎯':'target bullseye dart aim','🎳':'bowling ball strike pins',
  '🎮':'video game controller play','🎲':'dice roll game random chance',
  '♟️':'chess pawn strategy game board','🧩':'puzzle piece jigsaw fit',
  '🎭':'theater masks drama comedy tragedy','🎨':'art palette paint creative brush',
  '🎬':'movie clapper film action cinema','🎤':'microphone sing karaoke voice',
  '🎧':'headphones music listen audio','🎼':'music score notes sheet',
  '🎹':'piano keyboard music keys','🎸':'guitar music rock electric',
  '🎺':'trumpet music brass blow','🎷':'saxophone music jazz',
  '🎻':'violin music classical strings','🥁':'drums music beat percussion',
  '🏆':'trophy winner champion gold cup','🥇':'gold medal first place winner',
  '🥈':'silver medal second place','🥉':'bronze medal third place',
  '🏋️':'weightlifting gym strong barbell','🤸':'gymnastics acrobat cartwheel',
  '⛷️':'skiing snow mountain winter sport','🏄':'surfing wave ocean sport beach',
  '🚗':'car red automobile drive vehicle','🚕':'taxi yellow cab drive city',
  '🚌':'bus transport school public','🏎️':'race car fast formula sport',
  '🚓':'police car cop law enforcement','🚑':'ambulance emergency hospital',
  '🚒':'fire truck red engine emergency','✈️':'airplane plane fly travel airport',
  '🚀':'rocket space launch moon nasa','🛸':'ufo alien flying saucer space',
  '🚢':'ship cruise ocean sea sail','⛵':'sailboat wind ocean sea',
  '🚲':'bicycle bike ride cycle pedal','🛴':'scooter kick ride electric',
  '🏔️':'mountain peak snow tall climb','🌋':'volcano eruption lava fire',
  '🏖️':'beach sand sea vacation summer','🏜️':'desert sand dry hot camel',
  '🏝️':'island tropical beach palm alone','🏠':'house home building family',
  '🏢':'office building city work','🏥':'hospital medical health building',
  '🌃':'night city stars dark skyline','🏙️':'cityscape buildings skyline urban',
  '🌅':'sunrise morning sun horizon sky','🌉':'bridge night city lights water',
  '💡':'light bulb idea bright electricity','🔦':'flashlight torch light beam',
  '🕯️':'candle light flame wax','🔋':'battery power charge energy',
  '💻':'laptop computer work screen','📱':'phone mobile cell smartphone',
  '⌨️':'keyboard type computer keys','🖥️':'desktop monitor screen computer',
  '📷':'camera photo picture snap','📹':'video camera record film',
  '📺':'television tv screen watch show','📻':'radio music broadcast retro',
  '🔔':'bell ring notification alert','🔕':'bell off mute silent no sound',
  '📚':'books stack read study learn','📖':'open book read study page',
  '✏️':'pencil write draw sketch','📝':'memo note write pad list',
  '📌':'pushpin red map location mark','🔍':'magnifying glass search zoom find',
  '🔑':'key lock door open access','🔒':'lock closed secure private',
  '🔓':'lock open unlocked access','💰':'money bag dollar rich wealthy',
  '💳':'credit card payment swipe bank','💎':'diamond gem jewel precious',
  '⚖️':'scales justice balance law','🧲':'magnet attract metal pull',
  '🧪':'test tube science lab experiment','🔬':'microscope science biology lab',
  '🔭':'telescope space stars astronomy','🧬':'dna genetics biology science',
  '❤️':'red heart love passion romance','🧡':'orange heart warm care',
  '💛':'yellow heart happy friendship','💚':'green heart nature growth',
  '💙':'blue heart calm trust calm','💜':'purple heart royalty spiritual',
  '🖤':'black heart dark edgy gothic','🤍':'white heart pure peace',
  '💔':'broken heart sad heartbreak','💕':'two hearts love pink couple',
  '💖':'sparkling heart love glitter','💘':'heart arrow cupid love struck',
  '✨':'sparkles glitter shine magic stars','💥':'explosion boom impact bang',
  '🎉':'party popper celebrate confetti','🎊':'confetti ball celebrate party',
  '🎈':'balloon party birthday red float','🎁':'gift present wrap birthday',
  '🎃':'pumpkin halloween jack lantern','🎄':'christmas tree holiday lights',
  '🃏':'joker wild card game','🎰':'slot machine gamble casino luck',
  '🧠':'brain mind think smart knowledge','💊':'pill medicine tablet drug',
  '💉':'syringe injection vaccine medical','🩺':'stethoscope doctor medical',
  '🔮':'crystal ball magic future predict','🕵️':'detective spy magnify search sleuth',
  '👮':'police officer cop law badge','👷':'construction worker build hard hat',
  '🧙':'wizard magic wand spell witch','🧚':'fairy wings magic small pixie',
  '🧛':'vampire dracula blood bite gothic','🧜':'mermaid sea ocean tail fish',
  '🧝':'elf fantasy forest ears','🌍':'earth globe world europe africa',
  '🌎':'earth globe world americas','🌏':'earth globe world asia pacific',
  '🪐':'planet saturn rings space orbit','☀️':'sun bright star day warm glow',
  '🌙':'moon night crescent sleep dark','⭐':'star shine bright yellow night',
};

