let myName = localStorage.getItem('bsffr_name') || 'Player 1';
let myPlayerId = localStorage.getItem('bsffr_pid') || null;
let myCurrentRoomCode = localStorage.getItem('bsffr_room') || null;
let myIsHost = false;
let myIsImposter = false, myQuestion = null, mySubmitted = false, myVote = null;
let currentRoundNumber = 0, totalRoundsCount = 5;
let currentSubmissions = null;
let roomSettings = { rounds: 5, submitSeconds: 45, voteSeconds: 20, category: 'all', emojiSlots: 3, maxPlayers: 8 };
let nameModalCallback = null;
let socket = null, countdownId = null;
let currentScreen = 'lander', screenHistory = [];
let slots = [null, null, null], activeSlot = 0, currentCat = '😀';
